### ISSUE TITLE
Consider renaming this package

### ISSUE THREAD

**Issue by rulatir** [sdgluck/fetch-sync#6]
The name of this package misleadingly suggests that it provides a synchronous (i.e. non-"async") version of the `fetch()` API. This is not the case. The package has an entirely different purpose, and it does not provide synchronous interface. In a sense it is even more "async" than regular `fetch()`. Please consider renaming this package.

**Comment by sdgluck** [comment]
I will do asap. Thanks for raising.

**Comment by sdgluck** [comment]
NPM doesn't allow package renaming. Have renamed the repo.
